name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Docker Image
        run: docker build -t yolo11-streamlit .

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Tag and Push Image
        run: |
          docker tag yolo11-streamlit $DOCKER_USERNAME/yolo11-streamlit:latest
          docker push $DOCKER_USERNAME/yolo11-streamlit:latest

      - name: Deploy on Server (Optional)
        run: |
          ssh user@your-server-ip "docker pull $DOCKER_USERNAME/yolo11-streamlit:latest && docker run -d -p 8501:8501 $DOCKER_USERNAME/yolo11-streamlit"
